// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from testMessage.proto

package com.kevin.framework.generate.test;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.ByteString;
import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public final class ApiReqPacket implements Externalizable, Message<ApiReqPacket>, Schema<ApiReqPacket>
{

    public static Schema<ApiReqPacket> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static ApiReqPacket getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ApiReqPacket DEFAULT_INSTANCE = new ApiReqPacket();

    
    private Integer reqNum;
    private String methodName;
    private ByteString parameter;

    public ApiReqPacket()
    {
        
    }

    public ApiReqPacket(
        Integer reqNum,
        String methodName
    )
    {
        this.reqNum = reqNum;
        this.methodName = methodName;
    }

    // getters and setters

    // reqNum

    public Integer getReqNum()
    {
        return reqNum;
    }

    public void setReqNum(Integer reqNum)
    {
        this.reqNum = reqNum;
    }

    // methodName

    public String getMethodName()
    {
        return methodName;
    }

    public void setMethodName(String methodName)
    {
        this.methodName = methodName;
    }

    // parameter

    public ByteString getParameter()
    {
        return parameter;
    }

    public void setParameter(ByteString parameter)
    {
        this.parameter = parameter;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<ApiReqPacket> cachedSchema()
    {
        return this;
    }

    // schema methods

    public ApiReqPacket newMessage()
    {
        return new ApiReqPacket();
    }

    public Class<ApiReqPacket> typeClass()
    {
        return ApiReqPacket.class;
    }

    public String messageName()
    {
        return ApiReqPacket.class.getSimpleName();
    }

    public String messageFullName()
    {
        return ApiReqPacket.class.getName();
    }

    public boolean isInitialized(ApiReqPacket message)
    {
        return 
            message.reqNum != null 
            && message.methodName != null;
    }

    public void mergeFrom(Input input, ApiReqPacket message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.reqNum = input.readInt32();
                    break;
                case 2:
                    message.methodName = input.readString();
                    break;
                case 3:
                    message.parameter = input.readBytes();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, ApiReqPacket message) throws IOException
    {
        if(message.reqNum == null)
            throw new UninitializedMessageException(message);
        output.writeInt32(1, message.reqNum, false);

        if(message.methodName == null)
            throw new UninitializedMessageException(message);
        output.writeString(2, message.methodName, false);

        if(message.parameter != null)
            output.writeBytes(3, message.parameter, false);
    }

    public String getFieldName(int number)
    {
        switch(number)
        {
            case 1: return "reqNum";
            case 2: return "methodName";
            case 3: return "parameter";
            default: return null;
        }
    }

    public int getFieldNumber(String name)
    {
        final Integer number = __fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    private static final java.util.HashMap<String,Integer> __fieldMap = new java.util.HashMap<String,Integer>();
    static
    {
        __fieldMap.put("reqNum", 1);
        __fieldMap.put("methodName", 2);
        __fieldMap.put("parameter", 3);
    }
    
}
