// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from testMessage.proto

package com.kevin.framework.generate.test;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.util.ArrayList;
import java.util.List;

import com.dyuproject.protostuff.ByteString;
import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;
import com.dyuproject.protostuff.UninitializedMessageException;

public final class ApiTest implements Externalizable, Message<ApiTest>, Schema<ApiTest>
{

    public static Schema<ApiTest> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static ApiTest getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ApiTest DEFAULT_INSTANCE = new ApiTest();

    
    private Integer reqNum;
    private String methodName;
    private List<ByteString> parameter;

    public ApiTest()
    {
        
    }

    public ApiTest(
        Integer reqNum,
        String methodName
    )
    {
        this.reqNum = reqNum;
        this.methodName = methodName;
    }

    // getters and setters

    // reqNum

    public Integer getReqNum()
    {
        return reqNum;
    }

    public void setReqNum(Integer reqNum)
    {
        this.reqNum = reqNum;
    }

    // methodName

    public String getMethodName()
    {
        return methodName;
    }

    public void setMethodName(String methodName)
    {
        this.methodName = methodName;
    }

    // parameter

    public List<ByteString> getParameterList()
    {
        return parameter;
    }

    public void setParameterList(List<ByteString> parameter)
    {
        this.parameter = parameter;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<ApiTest> cachedSchema()
    {
        return this;
    }

    // schema methods

    public ApiTest newMessage()
    {
        return new ApiTest();
    }

    public Class<ApiTest> typeClass()
    {
        return ApiTest.class;
    }

    public String messageName()
    {
        return ApiTest.class.getSimpleName();
    }

    public String messageFullName()
    {
        return ApiTest.class.getName();
    }

    public boolean isInitialized(ApiTest message)
    {
        return 
            message.reqNum != null 
            && message.methodName != null;
    }

    public void mergeFrom(Input input, ApiTest message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.reqNum = input.readInt32();
                    break;
                case 2:
                    message.methodName = input.readString();
                    break;
                case 3:
                    if(message.parameter == null)
                        message.parameter = new ArrayList<ByteString>();
                    message.parameter.add(input.readBytes());
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, ApiTest message) throws IOException
    {
        if(message.reqNum == null)
            throw new UninitializedMessageException(message);
        output.writeInt32(1, message.reqNum, false);

        if(message.methodName == null)
            throw new UninitializedMessageException(message);
        output.writeString(2, message.methodName, false);

        if(message.parameter != null)
        {
            for(ByteString parameter : message.parameter)
            {
                if(parameter != null)
                    output.writeBytes(3, parameter, true);
            }
        }
    }

    public String getFieldName(int number)
    {
        switch(number)
        {
            case 1: return "reqNum";
            case 2: return "methodName";
            case 3: return "parameter";
            default: return null;
        }
    }

    public int getFieldNumber(String name)
    {
        final Integer number = __fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    private static final java.util.HashMap<String,Integer> __fieldMap = new java.util.HashMap<String,Integer>();
    static
    {
        __fieldMap.put("reqNum", 1);
        __fieldMap.put("methodName", 2);
        __fieldMap.put("parameter", 3);
    }
    
}
