// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from context.proto

package com.kevin.framework.generate.context;

import java.io.Externalizable;
import java.io.IOException;
import java.io.ObjectInput;
import java.io.ObjectOutput;

import com.dyuproject.protostuff.GraphIOUtil;
import com.dyuproject.protostuff.Input;
import com.dyuproject.protostuff.Message;
import com.dyuproject.protostuff.Output;
import com.dyuproject.protostuff.Schema;

public final class ApiContextMessage implements Externalizable, Message<ApiContextMessage>, Schema<ApiContextMessage>
{

    public static Schema<ApiContextMessage> getSchema()
    {
        return DEFAULT_INSTANCE;
    }

    public static ApiContextMessage getDefaultInstance()
    {
        return DEFAULT_INSTANCE;
    }

    static final ApiContextMessage DEFAULT_INSTANCE = new ApiContextMessage();

    
    private String ltsId;
    private String serialNo;
    private String mac;
    private String imei;
    private String imsi;
    private String resolution;
    private String density;
    private Integer screenWidth;
    private Integer screenHeight;
    private String deviceId;
    private String producer;
    private String model;
    private String firmware;
    private String osType;
    private String osVer;
    private String udid;
    private Integer clientVer;
    private String ttid;
    private Long firstInstalledAt;
    private Long lastInstalledAt;
    private Long firstActivatedAt;
    private String network;
    private String ip;
    private Long uid;
    private Long lastLoginAt;
    private String appKey;
    private String taoSid;
    private String taoEcode;
    private String location;
    private String installPath;
    private String ttidOriginal;

    public ApiContextMessage()
    {
        
    }

    // getters and setters

    // ltsId

    public String getLtsId()
    {
        return ltsId;
    }

    public void setLtsId(String ltsId)
    {
        this.ltsId = ltsId;
    }

    // serialNo

    public String getSerialNo()
    {
        return serialNo;
    }

    public void setSerialNo(String serialNo)
    {
        this.serialNo = serialNo;
    }

    // mac

    public String getMac()
    {
        return mac;
    }

    public void setMac(String mac)
    {
        this.mac = mac;
    }

    // imei

    public String getImei()
    {
        return imei;
    }

    public void setImei(String imei)
    {
        this.imei = imei;
    }

    // imsi

    public String getImsi()
    {
        return imsi;
    }

    public void setImsi(String imsi)
    {
        this.imsi = imsi;
    }

    // resolution

    public String getResolution()
    {
        return resolution;
    }

    public void setResolution(String resolution)
    {
        this.resolution = resolution;
    }

    // density

    public String getDensity()
    {
        return density;
    }

    public void setDensity(String density)
    {
        this.density = density;
    }

    // screenWidth

    public Integer getScreenWidth()
    {
        return screenWidth;
    }

    public void setScreenWidth(Integer screenWidth)
    {
        this.screenWidth = screenWidth;
    }

    // screenHeight

    public Integer getScreenHeight()
    {
        return screenHeight;
    }

    public void setScreenHeight(Integer screenHeight)
    {
        this.screenHeight = screenHeight;
    }

    // deviceId

    public String getDeviceId()
    {
        return deviceId;
    }

    public void setDeviceId(String deviceId)
    {
        this.deviceId = deviceId;
    }

    // producer

    public String getProducer()
    {
        return producer;
    }

    public void setProducer(String producer)
    {
        this.producer = producer;
    }

    // model

    public String getModel()
    {
        return model;
    }

    public void setModel(String model)
    {
        this.model = model;
    }

    // firmware

    public String getFirmware()
    {
        return firmware;
    }

    public void setFirmware(String firmware)
    {
        this.firmware = firmware;
    }

    // osType

    public String getOsType()
    {
        return osType;
    }

    public void setOsType(String osType)
    {
        this.osType = osType;
    }

    // osVer

    public String getOsVer()
    {
        return osVer;
    }

    public void setOsVer(String osVer)
    {
        this.osVer = osVer;
    }

    // udid

    public String getUdid()
    {
        return udid;
    }

    public void setUdid(String udid)
    {
        this.udid = udid;
    }

    // clientVer

    public Integer getClientVer()
    {
        return clientVer;
    }

    public void setClientVer(Integer clientVer)
    {
        this.clientVer = clientVer;
    }

    // ttid

    public String getTtid()
    {
        return ttid;
    }

    public void setTtid(String ttid)
    {
        this.ttid = ttid;
    }

    // firstInstalledAt

    public Long getFirstInstalledAt()
    {
        return firstInstalledAt;
    }

    public void setFirstInstalledAt(Long firstInstalledAt)
    {
        this.firstInstalledAt = firstInstalledAt;
    }

    // lastInstalledAt

    public Long getLastInstalledAt()
    {
        return lastInstalledAt;
    }

    public void setLastInstalledAt(Long lastInstalledAt)
    {
        this.lastInstalledAt = lastInstalledAt;
    }

    // firstActivatedAt

    public Long getFirstActivatedAt()
    {
        return firstActivatedAt;
    }

    public void setFirstActivatedAt(Long firstActivatedAt)
    {
        this.firstActivatedAt = firstActivatedAt;
    }

    // network

    public String getNetwork()
    {
        return network;
    }

    public void setNetwork(String network)
    {
        this.network = network;
    }

    // ip

    public String getIp()
    {
        return ip;
    }

    public void setIp(String ip)
    {
        this.ip = ip;
    }

    // uid

    public Long getUid()
    {
        return uid;
    }

    public void setUid(Long uid)
    {
        this.uid = uid;
    }

    // lastLoginAt

    public Long getLastLoginAt()
    {
        return lastLoginAt;
    }

    public void setLastLoginAt(Long lastLoginAt)
    {
        this.lastLoginAt = lastLoginAt;
    }

    // appKey

    public String getAppKey()
    {
        return appKey;
    }

    public void setAppKey(String appKey)
    {
        this.appKey = appKey;
    }

    // taoSid

    public String getTaoSid()
    {
        return taoSid;
    }

    public void setTaoSid(String taoSid)
    {
        this.taoSid = taoSid;
    }

    // taoEcode

    public String getTaoEcode()
    {
        return taoEcode;
    }

    public void setTaoEcode(String taoEcode)
    {
        this.taoEcode = taoEcode;
    }

    // location

    public String getLocation()
    {
        return location;
    }

    public void setLocation(String location)
    {
        this.location = location;
    }

    // installPath

    public String getInstallPath()
    {
        return installPath;
    }

    public void setInstallPath(String installPath)
    {
        this.installPath = installPath;
    }

    // ttidOriginal

    public String getTtidOriginal()
    {
        return ttidOriginal;
    }

    public void setTtidOriginal(String ttidOriginal)
    {
        this.ttidOriginal = ttidOriginal;
    }

    // java serialization

    public void readExternal(ObjectInput in) throws IOException
    {
        GraphIOUtil.mergeDelimitedFrom(in, this, this);
    }

    public void writeExternal(ObjectOutput out) throws IOException
    {
        GraphIOUtil.writeDelimitedTo(out, this, this);
    }

    // message method

    public Schema<ApiContextMessage> cachedSchema()
    {
        return this;
    }

    // schema methods

    public ApiContextMessage newMessage()
    {
        return new ApiContextMessage();
    }

    public Class<ApiContextMessage> typeClass()
    {
        return ApiContextMessage.class;
    }

    public String messageName()
    {
        return ApiContextMessage.class.getSimpleName();
    }

    public String messageFullName()
    {
        return ApiContextMessage.class.getName();
    }

    public boolean isInitialized(ApiContextMessage message)
    {
        return true;
    }

    public void mergeFrom(Input input, ApiContextMessage message) throws IOException
    {
        for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
        {
            switch(number)
            {
                case 0:
                    return;
                case 1:
                    message.ltsId = input.readString();
                    break;
                case 2:
                    message.serialNo = input.readString();
                    break;
                case 3:
                    message.mac = input.readString();
                    break;
                case 4:
                    message.imei = input.readString();
                    break;
                case 5:
                    message.imsi = input.readString();
                    break;
                case 6:
                    message.resolution = input.readString();
                    break;
                case 7:
                    message.density = input.readString();
                    break;
                case 8:
                    message.screenWidth = input.readInt32();
                    break;
                case 9:
                    message.screenHeight = input.readInt32();
                    break;
                case 10:
                    message.deviceId = input.readString();
                    break;
                case 11:
                    message.producer = input.readString();
                    break;
                case 12:
                    message.model = input.readString();
                    break;
                case 13:
                    message.firmware = input.readString();
                    break;
                case 14:
                    message.osType = input.readString();
                    break;
                case 15:
                    message.osVer = input.readString();
                    break;
                case 16:
                    message.udid = input.readString();
                    break;
                case 17:
                    message.clientVer = input.readInt32();
                    break;
                case 18:
                    message.ttid = input.readString();
                    break;
                case 19:
                    message.firstInstalledAt = input.readInt64();
                    break;
                case 20:
                    message.lastInstalledAt = input.readInt64();
                    break;
                case 21:
                    message.firstActivatedAt = input.readInt64();
                    break;
                case 22:
                    message.network = input.readString();
                    break;
                case 23:
                    message.ip = input.readString();
                    break;
                case 24:
                    message.uid = input.readInt64();
                    break;
                case 25:
                    message.lastLoginAt = input.readInt64();
                    break;
                case 26:
                    message.appKey = input.readString();
                    break;
                case 27:
                    message.taoSid = input.readString();
                    break;
                case 28:
                    message.taoEcode = input.readString();
                    break;
                case 29:
                    message.location = input.readString();
                    break;
                case 30:
                    message.installPath = input.readString();
                    break;
                case 31:
                    message.ttidOriginal = input.readString();
                    break;
                default:
                    input.handleUnknownField(number, this);
            }   
        }
    }


    public void writeTo(Output output, ApiContextMessage message) throws IOException
    {
        if(message.ltsId != null)
            output.writeString(1, message.ltsId, false);

        if(message.serialNo != null)
            output.writeString(2, message.serialNo, false);

        if(message.mac != null)
            output.writeString(3, message.mac, false);

        if(message.imei != null)
            output.writeString(4, message.imei, false);

        if(message.imsi != null)
            output.writeString(5, message.imsi, false);

        if(message.resolution != null)
            output.writeString(6, message.resolution, false);

        if(message.density != null)
            output.writeString(7, message.density, false);

        if(message.screenWidth != null)
            output.writeInt32(8, message.screenWidth, false);

        if(message.screenHeight != null)
            output.writeInt32(9, message.screenHeight, false);

        if(message.deviceId != null)
            output.writeString(10, message.deviceId, false);

        if(message.producer != null)
            output.writeString(11, message.producer, false);

        if(message.model != null)
            output.writeString(12, message.model, false);

        if(message.firmware != null)
            output.writeString(13, message.firmware, false);

        if(message.osType != null)
            output.writeString(14, message.osType, false);

        if(message.osVer != null)
            output.writeString(15, message.osVer, false);

        if(message.udid != null)
            output.writeString(16, message.udid, false);

        if(message.clientVer != null)
            output.writeInt32(17, message.clientVer, false);

        if(message.ttid != null)
            output.writeString(18, message.ttid, false);

        if(message.firstInstalledAt != null)
            output.writeInt64(19, message.firstInstalledAt, false);

        if(message.lastInstalledAt != null)
            output.writeInt64(20, message.lastInstalledAt, false);

        if(message.firstActivatedAt != null)
            output.writeInt64(21, message.firstActivatedAt, false);

        if(message.network != null)
            output.writeString(22, message.network, false);

        if(message.ip != null)
            output.writeString(23, message.ip, false);

        if(message.uid != null)
            output.writeInt64(24, message.uid, false);

        if(message.lastLoginAt != null)
            output.writeInt64(25, message.lastLoginAt, false);

        if(message.appKey != null)
            output.writeString(26, message.appKey, false);

        if(message.taoSid != null)
            output.writeString(27, message.taoSid, false);

        if(message.taoEcode != null)
            output.writeString(28, message.taoEcode, false);

        if(message.location != null)
            output.writeString(29, message.location, false);

        if(message.installPath != null)
            output.writeString(30, message.installPath, false);

        if(message.ttidOriginal != null)
            output.writeString(31, message.ttidOriginal, false);
    }

    public String getFieldName(int number)
    {
        switch(number)
        {
            case 1: return "ltsId";
            case 2: return "serialNo";
            case 3: return "mac";
            case 4: return "imei";
            case 5: return "imsi";
            case 6: return "resolution";
            case 7: return "density";
            case 8: return "screenWidth";
            case 9: return "screenHeight";
            case 10: return "deviceId";
            case 11: return "producer";
            case 12: return "model";
            case 13: return "firmware";
            case 14: return "osType";
            case 15: return "osVer";
            case 16: return "udid";
            case 17: return "clientVer";
            case 18: return "ttid";
            case 19: return "firstInstalledAt";
            case 20: return "lastInstalledAt";
            case 21: return "firstActivatedAt";
            case 22: return "network";
            case 23: return "ip";
            case 24: return "uid";
            case 25: return "lastLoginAt";
            case 26: return "appKey";
            case 27: return "taoSid";
            case 28: return "taoEcode";
            case 29: return "location";
            case 30: return "installPath";
            case 31: return "ttidOriginal";
            default: return null;
        }
    }

    public int getFieldNumber(String name)
    {
        final Integer number = __fieldMap.get(name);
        return number == null ? 0 : number.intValue();
    }

    private static final java.util.HashMap<String,Integer> __fieldMap = new java.util.HashMap<String,Integer>();
    static
    {
        __fieldMap.put("ltsId", 1);
        __fieldMap.put("serialNo", 2);
        __fieldMap.put("mac", 3);
        __fieldMap.put("imei", 4);
        __fieldMap.put("imsi", 5);
        __fieldMap.put("resolution", 6);
        __fieldMap.put("density", 7);
        __fieldMap.put("screenWidth", 8);
        __fieldMap.put("screenHeight", 9);
        __fieldMap.put("deviceId", 10);
        __fieldMap.put("producer", 11);
        __fieldMap.put("model", 12);
        __fieldMap.put("firmware", 13);
        __fieldMap.put("osType", 14);
        __fieldMap.put("osVer", 15);
        __fieldMap.put("udid", 16);
        __fieldMap.put("clientVer", 17);
        __fieldMap.put("ttid", 18);
        __fieldMap.put("firstInstalledAt", 19);
        __fieldMap.put("lastInstalledAt", 20);
        __fieldMap.put("firstActivatedAt", 21);
        __fieldMap.put("network", 22);
        __fieldMap.put("ip", 23);
        __fieldMap.put("uid", 24);
        __fieldMap.put("lastLoginAt", 25);
        __fieldMap.put("appKey", 26);
        __fieldMap.put("taoSid", 27);
        __fieldMap.put("taoEcode", 28);
        __fieldMap.put("location", 29);
        __fieldMap.put("installPath", 30);
        __fieldMap.put("ttidOriginal", 31);
    }
    
}
